---
- hosts: localhost
  connection: local
  sudo: yes
#
  roles: 
    - { role: ntp }
    - { role: splunkforwarder, when: "ansible_default_ipv4.address in groups['splunkgroup']"  }
    - { role: yum }
